
from nginx

RUN mkdir -p /usr/share/nginx/html
RUN ls /usr/share/nginx/html
COPY images/ /usr/share/nginx/html/images
COPY css/ /usr/share/nginx/html/css
COPY index.htm /usr/share/nginx/html

EXPOSE 443

