
version: '2'
services:
        marston.info:
            container_name: marston.info
            image:          nginx
            ports:
              - 443:443
            volumes:
              - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
              - ./frontend/html:/var/www/wedding.marston.info/html
              - ./frontend/css:/var/www/wedding.marston.info/html/css
              - ./frontend/images:/var/www/wedding.marston.info/html/images
              - /etc/letsencrypt/:/etc/letsencrypt/

        backend:
            container_name: backend
            environment:
              - AWS_PROFILE=submit
            image:          backend
            volumes:
              - /etc/aws/:/home/backend/.aws/


