
version: '2'
services:
        database:
            container_name: dynamo
            image:          dwmkerr/dynamodb
            networks:
                default:
                    ipv4_address: 172.18.0.3

        marston.info:
            container_name: marston.info
            image:          nginx
            ports:
              - 443:443
            volumes:
              - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
              - ./frontend/html:/var/www/testing.marston.info/html
              - ./frontend/notreadyyet.htm:/var/www/html/index.htm
              - ./frontend/css:/var/www/testing.marston.info/html/css
              - ./frontend/images:/var/www/testing.marston.info/html/images
              - /etc/letsencrypt/:/etc/letsencrypt/
            networks:
                default:
                    ipv4_address: 172.18.0.2
        backend:
            container_name: backend
            environment:
              - NODE_ENV=test
            image:          backend
            networks:
                default:
                    ipv4_address: 172.18.0.4
            volumes:
              - /etc/aws/:/home/backend/.aws/

networks:
    default:
        ipam:
          config:
            - subnet: 172.18.0.0/16
              gateway: 172.18.0.1


